### ISSUE TITLE
Generated gRPC application fails to compile with 3.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#971]
### Description

A fresh gRPC application created with `3.2.0-SNAPSHOT` fails to compile. The problem is that the latest micronaut-grpc changed `io.grpc:grpc-stub` from `api` to `implementation` so the library is not available to consumers anymore. 

### Steps to Reproduce

- `mn create-grpc-app foo`
- `cd foo`
- `./gradlew run`

### Expected Behaviour

The application should start 

### Actual Behaviour

```
> Task :compileJava FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:118: error: package io.grpc.stub does not exist
  public static final class Foo2ServiceStub extends io.grpc.stub.AbstractAsyncStub<Foo2ServiceStub> {
                                                                ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:141: error: package io.grpc.stub does not exist
  public static final class Foo2ServiceBlockingStub extends io.grpc.stub.AbstractBlockingStub<Foo2ServiceBlockingStub> {
                                                                        ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:163: error: package io.grpc.stub does not exist
  public static final class Foo2ServiceFutureStub extends io.grpc.stub.AbstractFutureStub<Foo2ServiceFutureStub> {
                                                                      ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:133: error: package io.grpc.stub does not exist
        io.grpc.stub.StreamObserver<foo2.Foo2Reply> responseObserver) {
                    ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:177: error: package com.google.common.util.concurrent does not exist
    public com.google.common.util.concurrent.ListenableFuture<foo2.Foo2Reply> send(
                                            ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:99: error: package io.grpc.stub does not exist
        io.grpc.stub.StreamObserver<foo2.Foo2Reply> responseObserver) {
                    ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:187: error: package io.grpc.stub.ServerCalls does not exist
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
                              ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:188: error: package io.grpc.stub.ServerCalls does not exist
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
                              ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:189: error: package io.grpc.stub.ServerCalls does not exist
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
                              ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:190: error: package io.grpc.stub.ServerCalls does not exist
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
                              ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:201: error: package io.grpc.stub does not exist
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
                                                ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:215: error: package io.grpc.stub does not exist
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
                    ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:214: error: package io.grpc.stub does not exist
    public io.grpc.stub.StreamObserver<Req> invoke(
                       ^
/home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/foo2/build/generated/source/proto/main/grpc/foo2/Foo2ServiceGrpc.java:20: error: package io.grpc.stub.annotations does not exist
  @io.grpc.stub.annotations.RpcMethod(
                           ^
14 errors
```

### Environment Information

- **Operating System**: Linux Mint 20.2
- **Micronaut Version:** 3.2.0-SNAPSHOT
- **JDK Version:** 8
